[[plugins]]
repo = 'Shougo/deoplete.nvim'
on_event = 'InsertEnter'
hook_source = '''
    " <TAB>: Completion
    inoremap <silent><expr> <TAB>
        \ pumvisible() ? "\<C-n>" :
        \ <SID>check_back_space() ? "\<TAB>" :
        \ deoplete#manual_complete()
    function! s:check_back_space() abort
        let col = col('.') - 1
        return !col || getline('.')[col - 1]  =~ '\s'
    endfunction
    " <S-TAB>: Completion back
    inoremap <expr><S-TAB> pumvisible() ? "\<C-p>" : "\<C-h>"
    smap <expr><TAB> neosnippet#expandable_or_jumpable() ?
        \ "\<Plug>(neosnippet_expand_or_jump)" : "\<TAB>"
    " Enable at start-up
    call deoplete#enable()
'''

[[plugins]]
repo = 'Shougo/neosnippet.vim'
depends = 'neosnippet-snippets'
on_event = 'InsertCharPre'
on_ft = 'snippet'
hook_source = '''
    " Plugin key-mappings.
    imap <C-f> <Plug>(neosnippet_expand_or_jump)
    smap <C-f> <Plug>(neosnippet_expand_or_jump)
    xmap <C-f> <Plug>(neosnippet_expand_target)
    " Personal snippets directory
    let g:neosnippet#snippets_directory = '~/.config/nvim/snippets'
'''

[[plugins]]
repo = 'alvan/vim-closetag'
on_ft = ['html','xhtml','phtml','htmldjango']
hook_source = '''
    let g:closetag_filenames = '*'
    let g:closetag_filetypes = '*'
'''

[[plugins]]
on_ft = ['json']
repo = 'elzr/vim-json'